name: Ejecuta Texto
on:
  workflow_dispatch:
    inputs:
      texto:
        description: 'Introduce un texto cualquiera'
        required: true
jobs:
  escritura:
    runs-on: ubuntu-latest
    steps:
      - name: Texto personalizado
        run: |
          echo "El texto introducido por el usuario es: ${{ github.event.inputs.texto }}!"
